#!/bin/sh
# watsonsvc daemon
# chkconfig: 345 20 80
# description: watsonsvc daemon
# processname: watsonsvc

DAEMON_PATH="/usr/bin"

DAEMON=watsonsvc

NAME=watsonsvc
DESC="Watson service"
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
        printf "%-50s" "Starting $NAME..."
        cd $DAEMON_PATH

        FILES=/etc/datawire/watson/*.conf
        for f in $FILES
        do
        echo "Processing $f ..."
        # take action on each file. $f store current file name
        /usr/bin/pkill -f $f
        /usr/bin/watson -c $f &
        done
        echo "ok";
        exit 0
;;
status)

CT=$(ps aux | grep watson | wc -l)

if [ $CT -gt "2" ]; then 
  echo "ok - $CT processes"
fi

;;
stop)
 #killall watson
 echo "Ok"
;;

reload)
        printf "%-50s" "Starting $NAME..."
        
        cd $DAEMON_PATH
        FILES=/etc/datawire/watson/*.conf
        for f in $FILES
        do
        echo "Processing $f ..."
        # take action on each file. $f store current file name
        echo "Stopping $f"
        /usr/bin/pkill -f $f
        echo "Starting watson $f" 
        /usr/bin/watson -c $f &
        sleep 1
        done
        exit 0
;;

*)
        echo "Usage: $0 {status|start|stop|restart|reload}"
        exit 1
esac
